version: '3'

services:
  app:
    build: .
    ports:
      - 8080:8080
    environment:
      - LOG_LEVEL=DEBUG
      - RABBIT_HOST=rabbitmq
      - RABBIT_PORT=5672
      - RABBIT_USERNAME=guest
      - RABBIT_PASSWORD=guest
    networks:
      fdk:
        aliases:
          - fdk-sparql-service

networks:
  fdk:
    name: fdk
