version: '3'

services:
  app:
    build: .
    ports:
      - 8080:8080
    environment:
      - LOG_LEVEL=DEBUG
    networks:
      fdk:
        aliases:
          - fdk-sparql-service

networks:
  fdk:
    name: fdk
