logging.level:
  root: ERROR
  no.fdk: DEBUG
application:
  fuseki:
    realm: fdk
    port: 8080
    context-path: fuseki
    store-path: store
    dataset-name: fdk
    enable-verbose-logging: false
  graph:
    datasets: ${GRAPH_BASE}/datasets/
    dataservices: ${GRAPH_BASE}/dataservices/
    concepts: ${GRAPH_BASE}/concepts/
    informationmodels: ${GRAPH_BASE}/informationmodels/
    events: ${GRAPH_BASE}/events/
    services: ${GRAPH_BASE}/services/
    uri: http://localhost:8080/fuseki/fdk
spring:
  kafka:
    bootstrap-servers:
      - ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    properties:
      schema.registry.url: ${KAFKA_SCHEMA_REGISTRY:http://localhost:8081}
      specific.avro.reader: true
      auto.register.schemas: false
      use.latest.version: true
      value.subject.name.strategy: io.confluent.kafka.serializers.subject.RecordNameStrategy
      key.subject.name.strategy: io.confluent.kafka.serializers.subject.RecordNameStrategy
    consumer:
      auto-offset-reset: earliest
      enable-auto-commit: false
      value-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
      max-poll-records: 5
    producer:
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
    listener:
      ack-mode: manual_immediate

---
spring:
  config.activate.on-profile: test
application:
  graph:
    datasets: https://staging.fellesdatakatalog.digdir.no/datasets/
    dataservices: https://staging.fellesdatakatalog.digdir.no/dataservices/
    concepts: https://staging.fellesdatakatalog.digdir.no/concepts/
    informationmodels: https://staging.fellesdatakatalog.digdir.no/informationmodels/
    events: https://staging.fellesdatakatalog.digdir.no/events/
    services: https://staging.fellesdatakatalog.digdir.no/services/
