logging.level:
  root: ERROR
  no.fdk: DEBUG
application:
  fuseki:
    realm: fdk
    port: 8080
    context-path: fuseki
    store-path: store
    dataset-names:
      - fdk
    enable-verbose-logging: false
  graph:
    datasets: ${GRAPH_BASE}/datasets/
    dataservices: ${GRAPH_BASE}/dataservices/
    concepts: ${GRAPH_BASE}/concepts/
    informationmodels: ${GRAPH_BASE}/informationmodels/
    events: ${GRAPH_BASE}/events/
    services: ${GRAPH_BASE}/services/
    uri: http://localhost:8080/fuseki/fdk

---
spring:
  config.activate.on-profile: test
application:
  graph:
    datasets: https://staging.fellesdatakatalog.digdir.no/datasets/
    dataservices: https://staging.fellesdatakatalog.digdir.no/dataservices/
    concepts: https://staging.fellesdatakatalog.digdir.no/concepts/
    informationmodels: https://staging.fellesdatakatalog.digdir.no/informationmodels/
    events: https://staging.fellesdatakatalog.digdir.no/events/
    services: https://staging.fellesdatakatalog.digdir.no/services/
