---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: prod
resources:
  - ../base

patchesStrategicMerge:
  - env.yaml

patches:
- patch: |-
    - op: replace
      path: /spec/storageClassName
      value: premium-rwo
  target:
    kind: PersistentVolumeClaim
    name: fdk-sparql-service