---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fdk-sparql-service
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: premium-rwo
  resources:
    requests:
      storage: 10Gi
