---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fdk-sparql-service
  labels:
    app: fdk-sparql-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fdk-sparql-service
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: fdk-sparql-service
      annotations:
        prometheus.io/scrape: "false"
    spec:
      containers:
        - name: fdk-sparql-service
          image: fdk-sparql-service
          imagePullPolicy: Always
          volumeMounts:
            - name: fuseki
              mountPath: /app/store
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /fuseki/$/ping
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 30
            successThreshold: 1
            failureThreshold: 5
          readinessProbe:
            httpGet:
              path: /fuseki/$/stats/fdk
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 30
            successThreshold: 1
            failureThreshold: 5
          resources:
            requests:
              memory: 9Gi
      securityContext:
        runAsUser: 1001
        runAsGroup: 1001
        fsGroup: 1001
      restartPolicy: Always
      volumes:
        - name: fuseki
          persistentVolumeClaim:
            claimName: fdk-sparql-service
