/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package no.fdk.event;
@org.apache.avro.specific.AvroGenerated
public enum EventEventType implements org.apache.avro.generic.GenericEnumSymbol<EventEventType> {
  EVENT_REASONED, EVENT_REMOVED, EVENT_HARVESTED  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"EventEventType\",\"namespace\":\"no.fdk.event\",\"symbols\":[\"EVENT_REASONED\",\"EVENT_REMOVED\",\"EVENT_HARVESTED\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
